### PR TITLE
Build both Debug and Release configurations for all major OS during CI

### PR DESCRIPTION
**Pull request by fredrikhr**
Modified the azure-pipelines template to build both the `Debug` and `Release` configurations for both `Windows` and `Linux` operating systems.

The solution uses a parameterized azure-pipeline template. This means that the OSs and Configurations can be configured in the Web UI when queueing a manual build.

I chose not to use the [`matrix` job strategy](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#matrix) in the template as the matrix-strategy as it did not allow me the fidelity I wanted when setting Display Names for the jobs. *E.g. note that OS is not a simple string, but an object containing the `vmImage` and a human readable `name`.*

I also found matrix strategies to be harder to reason about, while I suspect most programmers will understand a foreach-loop over a sequence.

**Update** (2020-05-26): added macOS build to the pipeline as well, so that all three major OSes are covered.

### CODE REVIEW

**Comment by terrajobst** [comment]
That looks sweet! Love this:

image

> **Question**: should we add a build for Mac OS as well? If so, just add the following lines to the `operatingSystems` `default` mapping:

We should, unless the builds will take longer.

**Comment by fredrikhr** [comment]
I added the `macOS` build to the pipeline. [PR description](https://github.com/terrajobst/minsk/pull/150#issue-422272088) has been updated.

**Comment by Nirmal4G** [comment]
I did this with **templates** but this does it in a single file. The only downside is, it gets harder to read and understand this, once it gets complicated. **But for now, this is better.**

**Comment by fredrikhr** [comment]
@Nirmal4G yeah, for more complex parts I also use templates in my projects ( https://github.com/thnetii/azure-pipelines/tree/master/templates ).

However, here this was simple enough and in the end it is easier to reason about when using only a single file instead of spreading this around across multiple files.

Also did you know that the values from the `parameter` section show up in the Web UI when manually queueing build runs? I.e. if you declared a boolean parameter, a checkbox would show up in UI, etc.

So yes, while the method here originally comes from build templates, Azure DevOps has evolved this model quite a bit allow for some pretty nice functionality.

**Pull request merged**
