### PR TITLE
Use pattern matching switch statement

### PR DESCRIPTION
**Pull request by y2k4life**
Simplify the switch statements and eliminates the need for casting

### CODE REVIEW

**Comment by terrajobst** [comment]
Hey @y2k4life! Thanks for the PR. Unfortunately, your change is going in the opposite direction of where I want to go. [This morning, I was moving from the try-cast pattern to this switch statement](https://youtu.be/EEzuO9XWmUY?list=PLRAdsfhKI4OWNOSfS7EUu5GRAVmze1t2y&t=2876).

While your code *looks* like it's the same as a `switch` statement, it's really not. It basically compiles to something like this:

```C#
if (node != null)
{
    BoundLiteralExpression boundLiteralExpression;
    if ((boundLiteralExpression = (node as BoundLiteralExpression)) == null)
    {
        BoundNameExpression boundNameExpression;
        if ((boundNameExpression = (node as BoundNameExpression)) == null)
        {
            BoundAssignmentExpression boundAssignmentExpression;
            if ((boundAssignmentExpression = (node as BoundAssignmentExpression)) == null)
            {
                BoundBinaryExpression boundBinaryExpression;
                if ((boundBinaryExpression = (node as BoundBinaryExpression)) == null)
                {
                    BoundUnaryExpression boundUnaryExpression;
                    if ((boundUnaryExpression = (node as BoundUnaryExpression)) != null)
                    {
                        BoundUnaryExpression j = boundUnaryExpression;
                        return Program.EvaluateUnaryExpression(j);
                    }
                    return null;
                }
                BoundBinaryExpression k = boundBinaryExpression;
                return Program.EvaluateBinaryExpression(k);
            }
            BoundAssignmentExpression m = boundAssignmentExpression;
            return Program.EvaluateAssignmentExpression(m);
        }
        BoundNameExpression l = boundNameExpression;
        return Program.EvaluateNameExpression(l);
    }
    BoundLiteralExpression i = boundLiteralExpression;
    return Program.EvaluateLiteralExpression(i);
}
``` 

The current `switch` statement uses the integer value of the enum to jump directly to the corresponding label, which is more efficient once we add more nodes to it. Any solution (modulo a proper visitor pattern) will need a cast; but in my switch there will be a single cast while the pattern-based switch requires multiple casts in order to see which label to use.

Does this make sense?

**Comment by y2k4life** [comment]
Yes it does. I went of on a tangent to see compiled code. I wrote a simple console app with the core parts we are looking at. It looks like the casting and testing is done in one instruction `isinst`.  If it is not true then it moves to the next possibility having to do another casting and repeats. What I found interesting is there are multiple castings or there are multiple calls to `get_Kind()`. But I'm sure the call to the function is more efficient than casting.

Why when compiled down casting and testing of the type done all at once? Could the testing of the type be done with out the casting and only cast if the results is true? I tried some things using `Name` property with `typeof` and `GetType`.

I chalk this one up as syntactic sugar. It is interesting, where I have pattern matching I could add a `Kind` property and a `Kinds` enum and use that for pattern testing which might be more efficient versus readability and what appears to be simplicity.

```
  IL_0030:  ldloc.0
  IL_0031:  isinst     ConsoleApp.BoundBinaryExpression
  IL_0036:  dup
  IL_0037:  stloc.s    V_4
  IL_0039:  brfalse.s  IL_003d    // branch to the next test which performs another casting
  IL_003b:  br.s       IL_007c
.
.
.
  IL_007c:  ldloc.s    V_4
  IL_007e:  stloc.s    V_9
  IL_0080:  br.s       IL_0082
  IL_0082:  ldloc.s    V_9
  IL_0084:  call       object ConsoleApp.Program::EvaluateBinaryExpression(class ConsoleApp.BoundBinaryExpression)
  IL_0089:  stloc.s    V_12
  IL_008b:  br.s       IL_00a3
```
The `if` based on a `enum` would only do the casting only when `true`
```
  IL_0039:  ldarg.0
  IL_003a:  callvirt   instance valuetype ConsoleApp.BoundNodeKind ConsoleApp.BoundExpression::get_Kind()
  IL_003f:  ldc.i4.2
  IL_0040:  ceq
  IL_0042:  stloc.3
  IL_0043:  ldloc.3
  IL_0044:  brfalse.s  IL_0055          // branch to the next if statement skipping the casting
  IL_0046:  nop
  IL_0047:  ldarg.0
  IL_0048:  castclass  ConsoleApp.BoundAssignmentExpression
  IL_004d:  call       object ConsoleApp.Program::EvaluateAssignmentExpression(class ConsoleApp.BoundAssignmentExpression)
  IL_0052:  stloc.1
  IL_0053:  br.s       IL_0095             // branch to the end
```
I even looked at the complex `if` statements you show above. Which has similar results as the `switch`
```
  IL_0046:  ldarg.0
  IL_0047:  isinst     ConsoleApp.BoundBinaryExpression
  IL_004c:  dup
  IL_004d:  stloc.s    V_10
  IL_004f:  ldnull
  IL_0050:  ceq
  IL_0052:  stloc.s    V_12
  IL_0054:  ldloc.s    V_12
  IL_0056:  brfalse.s  IL_0080
.
.
.
  IL_0080:  ldloc.s    V_10
  IL_0082:  stloc.s    V_11
  IL_0084:  ldloc.s    V_11
  IL_0086:  call       object ConsoleApp.Program::EvaluateBinaryExpression(class ConsoleApp.BoundBinaryExpression)
  IL_008b:  stloc.s    V_16
  IL_008d:  br.s       IL_00be

**Comment by y2k4life** [comment]
Still not done. I might be done after this though. It is just a bothersome to me that something that was introduced in C# to help actually might not be helpful.

Reading ECMA-335 it is hard to read exactly what is going on with `isinst`, but to me it looks like it will not do casting if it is not the correct type. I don't think it is, try casting and if it fails then it is not the type. I think it is if this is the type then cast.

>isinst typeTok 
>
>The isinst instruction tests whether obj (type O) is an instance of the type typeTok.  If the actual type (not the verifier tracked type) of obj is verifier-assignable-to the type typeTok then isinst succeeds and obj (as result) is returned unchanged while verification tracks its type as typeTok. Unlike coercions (§III.1.6) and conversions (§III.3.27), isinst never changes the actual type of an object and preserves object identity (see Partition I). If obj is null, or obj is not verifier-assignable-to the type typeTok, isinst fails and returns null.

**Comment by terrajobst** [comment]
> I know this has nothing to do with compiler but it is an interesting rabbit trail.

Well, it sort of does. While we're not emitting IL yet, that's exactly the kind of stuff that compiler authors think about! I love the fact that you benchmark.

The jump table of the switch tends to be more efficient then several casts in a row; however, keep in mind that we only have five nodes here, which is tiny. My finished compiler has 21 (still quite small) while [Roslyn has 160](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Generated/BoundNodes.xml.Generated.cs,2ad37a5770330ec1). However, Roslyn uses neither the pattern matching nor the switch; they use a visitor pattern, like so:

````C#
class BoundTreeVisitor
{
    public virtual VisitLiteralExpression(BoundLiteralExpression node) {}
    public virtual VisitVariableExpression(BoundVariableExpression node) {}
    public virtual VisitAssignmentExpression(BoundAssignmentExpression node) {}
    public virtual VisitBinaryExpression(BoundBinaryExpression node) {}
    public virtual VisitUnaryExpression(BoundUnaryExpression node) {}
}

class BoundNode
{
    public abstract void Accept(BoundTreeVisitor visitor);
}

public class BoundLiteralExpression : BoundNode
{
    public overide void Accept(BoundTreeVisitor visitor) => visitor.VisitLiteralExpression(this);
}

public class BoundVariableExpression : BoundNode
{
    public overide void Accept(BoundTreeVisitor visitor) => visitor.VisitVariableExpression(this);
}

public class BoundAssignmentExpression : BoundNode
{
    public overide void Accept(BoundTreeVisitor visitor) => visitor.VisitAssignmentExpression(this);
}

public class BoundBinaryExpression : BoundNode
{
    public overide void Accept(BoundTreeVisitor visitor) => visitor.VisitBinaryExpression(this);
}

public class BoundUnaryExpression : BoundNode
{
    public overide void Accept(BoundTreeVisitor visitor) => visitor.VisitUnaryExpression(this);
}
```

This technique requires no casting, but the cost is now two virtual method calls. Personally, I'm not a fan of the visitor approach. It feels fairly heavy weight and also makes it hard to control how the traversal happens and what the result types are.

**Comment by y2k4life** [comment]
The old GoF. I always have the challenge of knowing what to use, where to use it, and when to use it.

Thank you for these videos gives me a break from my day job to dive into some theory. This coincides with finding old C64 assembly language books. I know there are a lot of compilers out there for the 6510 but I'm thinking of building my own based on your videos. Heck why not.

I could not let the idea of the `switch` Pattern Matching go. I did some more testing. Instead of dumping more into this thread I started a project to share my results, thoughts and test code.

[Test Control Logic](https://github.com/y2k4life/TestControlLogic)

## Conclusion
> Efficiency does not always mean faster.

> Watch out for syntactic sugar.

**Comment by terrajobst** [comment]
> I could not let the idea of the `switch` Pattern Matching go.

I think pattern matching is definitely easier to read. If C# ever gets discriminated types, it could even be made as efficient as my manual switch over the kind. And to be honest, in this compiler projects optimizing isn't the higher order anyways. The primary reason of me using it has probably more to do with habit and symmetry as with creating efficient code. In the end, there are plenty of other areas in this compiler that are far from being efficient too :-)


> I know there are a lot of compilers out there for the 6510 but I'm thinking of building my own based on your videos. Heck why not.

Sounds like a great project! Consider streaming it. There isn't a lot of videos out there on this subject. And I'm completely selfish here as I'd likely watch yours :-)

**Comment by ltrzesniewski** [comment]
> `N` is the number of times I called the method. Where `expression = BoundUnaryExpression` which is the last case statement in both methods.

You may have fallen into a subtle trap there. You've essentially trained the [branch predictor](https://stackoverflow.com/a/11227902/3764814) that the last option is always right.
If you use a random sequence of actual types in your benchmark, I think you may see _very_ different results.

**Comment by y2k4life** [comment]
I updated my code to have a random tests. While I was doing that I noticed there was an issue with calling the same method for both enum and pattern match. Making the test result null and void.

With the update there is a performance difference and **Pattern Matching is faster!!!!**
Faster may not always more efficient. I will run these again once we add more possibilities to it.

>Sounds like a great project! Consider streaming it. There isn't a lot of videos out there on this subject. And I'm completely selfish here as I'd likely watch yours :-)

Once you are done with a compile I build from I will consider doing some videos.

``` ini

BenchmarkDotNet=v0.11.2, OS=Windows 10.0.17134.345 (1803/April2018Update/Redstone4)
Intel Core i7-7820HK CPU 2.90GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=2.1.500-preview-009335
  [Host]     : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Core 2.1.5 (CoreCLR 4.6.26919.02, CoreFX 4.6.26919.02), 64bit RyuJIT


```
|                         Method |      N |      Mean |     Error |    StdDev |
|------------------------------- |------- |----------:|----------:|----------:|
|        **Switch_Pattern_Matching** | **100000** |  **1.197 ms** | **0.0227 ms** | **0.0270 ms** |
|            Switch_Enum_Casting | 100000 |  1.538 ms | 0.0243 ms | 0.0227 ms |
|            If_Pattern_Matching | 100000 |  1.157 ms | 0.0230 ms | 0.0264 ms |
|                If_Enum_Casting | 100000 |  1.862 ms | 0.0170 ms | 0.0159 ms |
| **Random_Switch_Pattern_Matching** | **100000** | **14.768 ms** | **0.3329 ms** | **0.3963 ms** |
|     Random_Switch_Enum_Casting | 100000 | 15.258 ms | 0.3213 ms | 0.4709 ms |
|     Random_If_Pattern_Matching | 100000 | 14.579 ms | 0.2749 ms | 0.2572 ms |
|         Random_If_Enum_Casting | 100000 | 15.322 ms | 0.0943 ms | 0.0787 ms |
|        **Switch_Pattern_Matching** | **500000** |  **5.778 ms** | **0.0564 ms** | **0.0527 ms** |
|            Switch_Enum_Casting | 500000 |  7.697 ms | 0.0803 ms | 0.0671 ms |
|            If_Pattern_Matching | 500000 |  5.627 ms | 0.0251 ms | 0.0222 ms |
|                If_Enum_Casting | 500000 |  9.297 ms | 0.0438 ms | 0.0388 ms |
| **Random_Switch_Pattern_Matching** | **500000** | **71.938 ms** | **0.7353 ms** | **0.6878 ms** |
|     Random_Switch_Enum_Casting | 500000 | 75.282 ms | 0.9671 ms | 0.9046 ms |
|     Random_If_Pattern_Matching | 500000 | 72.064 ms | 0.4969 ms | 0.4405 ms |
|         Random_If_Enum_Casting | 500000 | 76.534 ms | 0.7372 ms | 0.6536 ms |

**Comment by terrajobst** [comment]
> With the update there is a performance difference and **Pattern Matching is faster!!!!**

@y2k4life, could you share the code? That seems rather odd. It's conceivable that the jump table has overhead that happens to be larger than a naive sequence of if checks when the number of comparisons is small (such as in our case where it's just five).

**Pull request closed without merging**
